### ISSUE TITLE
Mal Formed Array

### ISSUE THREAD

**Issue by Deamoner** [regican/Salesforce#1]
I loaded this library and setup the config file but it is saying "Malformed array" and won't run codeigniter now. I can't seem to find any issues in the config file, any ideas?

**Comment by mdelgaudio** [comment]
I've found a number of config issues in the library -- that should fix the "Array Malformed" issue. 
In the salesforce library the config items needed to be reformatted like:

``` php
$this->config->item('sfdc_client_id', 'salesforce');
```

For example my oauth array now look like this:

``` php
        $this->oauth    = array(
               'client_id'      =>  $this->config->item('sfdc_client_id', 'salesforce'),
               'client_secret'  =>  $this->config->item('sfdc_client_secret', 'salesforce'),
               'grant_type' =>  $this->config->item('sfdc_grant_type', 'salesforce'),
               'username'       =>  $this->config->item('sfdc_username', 'salesforce'),
               'password'       =>  $this->config->item('sfdc_password', 'salesforce').$this->config->item('sfdc_security_token', 'salesforce')
        );
```

look around for the config items, they may also be disguised like $this->api_version, which should become 

``` php
$this->config->item('sfdc_api_version', 'salesforce')
```

**Comment by mdelgaudio** [comment]
ANother note that confused me, it appears that 

``` php
$config['sfdc_code'] = '';
```

can be left blank in the config file itself... I cannot find an appropriate value to put in there. and when I put in dummy text, nothing happens. 

It's worth noting that `sfdc_code` doesn't appear anywhere in the actual salesforce library, so I'm not sure what it's for,

**Comment by regican** [comment]
Sorry guys, i'm only seeing this now. I wasn't an active Github user and was just testing the grounds before. However, this repo has been changed a lot since I first made it. I'll update these files soon.
